[project]
name = "gamename"
title = "Game Name"
version = "0.1.0"
authors = ["Kevin Fischer"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "3.0"
edition = "pro"

[dependencies]
